steps:
- name: "gcr.io/cloud-builders/docker"
  args: ["build", "-t", "gcr.io/$PROJECT_ID/gcp-docker-image-values-service", "."]
  id: "build image"
- name: "gcr.io/cloud-builders/docker"
  args: ["push", "gcr.io/$PROJECT_ID/gcp-docker-image-values-service"]
  id: "push image"
- name: "gcr.io/cloud-builders/kubectl"
  args:
  - "apply"
  - "-f"
  - "kubernetes/deployment.yaml"
  id: "deploy"
images:
- "gcr.io/$PROJECT_ID/gcp-docker-image-values-service"
