apiVersion: apps/v1
kind: Deployment
metadata:
  name: values-service-k8s-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: values-service
  template:
    metadata:
      labels:
        app: values-service
    spec:
      containers:
        - name: values-service
          image: gcr.io/values-service-gcp-project/gcp-docker-image-values-service:latest
          ports:
            - containerPort: 80
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
          resources:
            limits:
              cpu: 256m
              memory: 256Mi
            requests:
              cpu: 128m
              memory: 128Mi
