apiVersion: apps/v1
kind: Deployment
metadata:
  name: values-service-k8s-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: values-service
  template:
    metadata:
      labels:
        app: values-service
    spec:
      containers:
        - name: values-service
          image: gcr.io/$_PROJECT_ID/gcp-docker-image-values-service
          ports:
            - containerPort: 80
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 250m
              memory: 256Mi
