apiVersion: v1
kind: Service
metadata:
  name: load-balancer-service
spec:
  type: LoadBalancer
  selector:
    app: values-service
  ports:
    - name: http
      port: 80
      targetPort: 80
